const restful = require('node-restful')
const mongoose = restful.mongoose

const cotacao = new mongoose.Schema({
	cot_numero_ordem			:{type:String},
	cot_seq_ordem					:{type:Number},
	cot_seq_cotac					:{type:Number},
	cot_it_codigo					:{type:String},
	cot_desc_item					:{type:String},
	cot_un								:{type:String},
	cot_cod_moeda					:{type:String},
	cot_des_moeda					:{type:String},
	cot_cod_fornec				:{type:String},	
	cot_nome_abrev_fornec	:{type:String},
	cot_nome_fornec				:{type:String},
	cot_cnpj_fornec				:{type:String},
	cot_cot_aprovada			:{type:String},	
	cot_data_cotacao			:{type:String},	
	cot_dias_validade			:{type:String},	
	cot_usuario						:{type:String},
	cot_contato						:{type:String},
	cot_comprador					:{type:String},
	cot_preco							:{type:Number},
	cot_valor_ipi					:{type:Number},	
	cot_preco_unit				:{type:Number},
	cot_aliquota_ii				:{type:String},
	cot_sla_cotacao_oc		:{type:String},
})

const item_nota = new mongoose.Schema({
	itn_serie                    :{type:String},
	itn_numero_nota              :{type:String},
	itn_cod_fornec               :{type:String},
	itn_cod_nat_oper             :{type:String},
	itn_sequencia                :{type:String},
	itn_it_codigo                :{type:String},
	itn_num_pedido               :{type:String},
	itn_numero_ordem             :{type:String},
	itn_parcela                  :{type:String},
	itn_quantidade               :{type:String},
	itn_qt_do_forn               :{type:String},
	itn_un                       :{type:String},
	itn_preco_total              :{type:String},
	itn_natureza_fiscal          :{type:String},
	itn_valor_ipi                :{type:String},
	itn_narrativa                :{type:String},
	itn_nome_abrev_fornec        :{type:String},
	itn_nome_fornec              :{type:String},
	itn_cnpj_fornec              :{type:String},
	itn_des_nat_oper             :{type:String},
	itn_cod_estabel              :{type:String},
	itn_dt_emissao               :{type:String},
	itn_dt_trans                 :{type:String},
	itn_dt_atualiza              :{type:String},
	itn_cod_chave_aces_nf_eletro :{type:String},
	itn_idi_sit_nf_eletro        :{type:String},
	itn_tot_valor                :{type:String}
})


const parcela = new mongoose.Schema({
	par_numero_ordem:{type:String},	
	par_seq_ordem		:{type:Number},	
	par_it_codigo		:{type:String},	
	par_desc_item		:{type:String},	
	par_parcela			:{type:String},	
	par_quantidade	:{type:Number},	
	par_quant_receb	:{type:Number},	
	par_quant_devol	:{type:Number},	
	par_data_entrega:{type:String},		
	par_quant_saldo	:{type:Number},	
	par_quant_aloc	:{type:Number},	
	par_situacao		:{type:String},
	par_item_nota	  :[item_nota]
})






const compraSchema = new mongoose.Schema({
    nr_requisicao			:{type:String},	
		aprovador					:{type:String},	
		requisitante			:{type:String},	
		estado_sc					:{type:String},	
		situacao_sc				:{type:String},	
		sequencia					:{type:Number},	
		it_codigo					:{type:String},	
		desc_item					:{type:String},	
		cod_estabel				:{type:String},	
		nome_estabel			:{type:String},	
		cod_cta_ctbl			:{type:String},	
		des_cta_ctbl			:{type:String},	
		cod_ccusto				:{type:String},	
		des_ccusto				:{type:String},	
		cod_unid_negoc		:{type:String},	
		des_unid_negoc		:{type:String},	
		cod_depos					:{type:String},	
		cod_localiz				:{type:String},	
		lote							:{type:String},	
		dt_entrega				:{type:String},	
		numero_ordem			:{type:String},	
		num_ord_inv				:{type:String},	
		qt_a_atender			:{type:Number},	
		un								:{type:String},	
		narrativa					:{type:String},
		sla_aprov_mro			:{type:String},
		data_aprov_mro		:{type:String},
		sla_aprov_ctrl		:{type:String},
		data_aprov_ctrl		:{type:String},
		aprovador_ctrl		:{type:String},
		sla_aprov_financ	:{type:String},
		data_aprov_financ	:{type:String},
		aprovador_financ	:{type:String},
		sla_emissao_oc		:{type:String},
		data_emissao_oc		:{type:String},
		emissor_oc				:{type:String},
		dt_requisicao			:{type:String},
		nr_svi						:{type:Number},
		ordem_compra	: {
			oc_numero_ordem				:{type:String},
			oc_sequencia					:{type:Number},
			oc_cod_fornec					:{type:Number},
			oc_nome_abrev_fornec	:{type:String},
			oc_nome_fornec				:{type:String},
			oc_cnpj_fornec				:{type:String},
			oc_it_codigo					:{type:String},
			oc_desc_item					:{type:String},
			oc_qt_solic						:{type:Number},
			oc_cod_estabel				:{type:String},
			oc_nome_estabel				:{type:String},	
			oc_des_cond_pag				:{type:String},	
			oc_num_pedido					:{type:Number},	
			oc_comprador					:{type:String},	
			oc_requisitante				:{type:String},	
			oc_data_pedido				:{type:String},
			oc_data_emissao				:{type:String},	
			oc_local_emtrega			:{type:String},	
			oc_nr_requisicao			:{type:Number},	
			oc_cod_moeda					:{type:String},
			oc_des_moeda					:{type:String},
			oc_preco							:{type:String},
			oc_situacao						:{type:String},	
			oc_cod_cta_ctbl				:{type:String},	
			oc_des_cta_ctbl				:{type:String},	
			oc_cod_ccusto					:{type:String},
			oc_des_ccusto					:{type:String},	
			oc_endereco						:{type:String},	
			oc_narrativa					:{type:String},	
			oc_sla_emissao				:{type:String},
			oc_emissor						:{type:String},	
			oc_sla_cotacao				:{type:String},		
			oc_data_cotacao				:{type:String},	
			oc_usuario_cotacao		:{type:String},	
			oc_sla_pedido					:{type:String},	
			oc_responsavel_pedido	:{type:String}
		},
		cotacao			: [cotacao], 
		parcela			: [parcela],
		pedido_compr	: {
			ped_num_pedido		 		:{type:String},	
			ped_data_pedido		 		:{type:String},	
			ped_cod_fornec		 		:{type:String},	
			ped_nome_abrev_fornec	:{type:String},
			ped_nome_fornec		 		:{type:String},	
			ped_cnpj_fornec		 		:{type:String},	
			ped_situacao		 			:{type:String},	
			ped_natureza		 			:{type:String}
		}
})

module.exports = restful.model('compra', compraSchema)
